/* Configuration for ml_kem_ada_tests generated by Alire */
#ifndef ML_KEM_ADA_TESTS_CONFIG_H
#define ML_KEM_ADA_TESTS_CONFIG_H

#define CRATE_VERSION "0.0.0"
#define CRATE_NAME "ml_kem_ada_tests"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
